OgrFileExport: Fix build with GDAL_DEBUG set
With GDAL_DEBUG set, the compilation fails with
"ogr_file_format.cpp:465:141: error: cannot convert ‘OGRDataSourceH’
{aka ‘OGRDataSourceHS*’} to ‘OGRSpatialReferenceH’ {aka
‘OGRSpatialReferenceHS*’}".  The flag is defined by GDAL itself for
CMake debug targets.

This patch makes the code use the newer GDAL API and rectifies the data
type usage.